// export const passage = `
// Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent metus arcu, gravida id auctor et, tincidunt eget neque. Maecenas enim orci, laoreet et enim pellentesque, venenatis volutpat leo. Quisque at elementum leo. Morbi molestie orci eget justo pharetra suscipit. Donec eget tortor nulla. Nulla molestie, nisl fermentum consequat rhoncus, magna risus faucibus nulla, et bibendum risus nibh vel tellus. Nam cursus lectus mi, ut consequat ipsum gravida et. Curabitur lobortis consectetur mauris sed tincidunt. Ut eu sollicitudin dolor. Sed erat est, pretium id massa interdum, pharetra gravida mauris. Maecenas vel felis enim. Morbi tincidunt euismod erat mollis elementum. Etiam magna libero, elementum sit amet ipsum vel, viverra rhoncus turpis.

// Sed non nulla id est gravida cursus a et ante. Nulla interdum nulla elit, sed aliquam nulla placerat ut. Donec vitae ante blandit, porta libero quis, dapibus ex. Curabitur quam magna, luctus sed laoreet elementum, ultrices ut felis. Maecenas eu porta mauris. Phasellus nibh magna, viverra ac euismod id, eleifend posuere mauris. Cras erat dolor, scelerisque non nunc ut, vestibulum condimentum metus. Ut a sapien sed tortor pulvinar hendrerit sed ac nibh. Nullam consequat turpis at tellus malesuada vehicula. Etiam convallis blandit sollicitudin. Pellentesque blandit ac lorem eu molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

// Vivamus non diam ac ante sollicitudin gravida. Cras malesuada consectetur massa eget suscipit. Ut non diam a tellus imperdiet posuere sit amet euismod lacus. Quisque vehicula nibh dolor, quis volutpat urna rhoncus eget. Aenean scelerisque purus vel hendrerit condimentum. Maecenas in auctor neque. Suspendisse potenti.

// Suspendisse libero orci, facilisis vitae erat in, rhoncus consequat tortor. Vivamus in nibh orci. Duis blandit semper euismod. Nunc pulvinar justo augue, et facilisis libero iaculis eget. Aliquam congue tellus ut dui varius, eu egestas mauris dignissim. Duis vestibulum diam elit, non malesuada arcu ultricies quis. Nullam ac quam justo. In hac habitasse platea dictumst. Fusce scelerisque orci turpis, nec egestas ex sodales ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce eu malesuada libero, sit amet lobortis ligula. Praesent vel nibh fermentum, malesuada lorem vel, pharetra ante. Curabitur magna nisl, varius a ultricies eu, pellentesque tempus justo.

// Vivamus nec facilisis risus. Cras vestibulum turpis nibh, sit amet sagittis mauris posuere ornare. Donec nec elementum augue. In tristique magna eu metus interdum, at dignissim enim tempor. Suspendisse rhoncus eros eros, ac scelerisque nibh sollicitudin eget. Vivamus lacus magna, pulvinar et iaculis ac, egestas quis magna. Donec pulvinar tincidunt arcu, ac tincidunt mauris. Pellentesque sed neque et velit maximus efficitur. Nullam vitae tortor eu erat scelerisque dignissim in a ex. Ut eleifend consectetur euismod. Nulla consectetur lacus eget nunc feugiat ultrices.
// `;
export const passage = `
The question of mental efficiensy is in the air. It touches you nearly. Your conscience tells you that your mind is less active and less enformed than it might be. You sudenly spring up from the garden-seat, and you say to yourself that yue will take your mind in hand and do something with it. Wait a moment. Be so good as to sink back into that garden-seat and clutch that tennis racket a little longer. You have these “hours of insight” befor, you know. You have not arrived at the age of thirtie without having tried to carry out noble resolusions, and failed. What precautions are you going to take against failere this time? For your will is probebly no stronger now that it was before. You have admitted and acepted failure in the past. And no wound is more cruel to the spirit of resolv than that delt by failure. You fancy the wound closed but just at the critical moment it may reopen and mortally blead you. What are your precautions? have you thought of them? No. You have not. 

I have not the pleasure of you aquaintance. But I know you because I know myselve. Your failure in the past was due to one or more of these three cauces. And the first was that you undertook too much at the beginning. You started off with a magnificent program. You are something of an expert in physical exersices - you would be ashamed not be, in these physical days - and so you would never attempt a hurdle race or an uninterrupted hour’s club whirling without some preparation. The analogy between the body and the mind out to have struck you. This time, please do not form an elaberate program. Do not form any program. Simply contact yourself with a preliminery canter. For example (and I give merely as an exampel), you might say to yourself: “Within one month from this date I will read twice Herbert Spencer’s little book on “Education’ and will make notes in pencil inside the back cover of the things that particilary strike me.”  You remark that that is nothing. Well, do it. When it is done you will at any rate possess the satisfaction of having resolved to do something and having done it. Your mind will have gained tone and healthy pride. You will be even justified in setting yourself some kind of simpl program to extend over three months. And you will have acquired some general principals by the light of which to construct the program. But best of all, you will have avoid failure, that dangerous woond.

The second posible cause of previous failure was the disintegrating effect on the will-power of the irionic, superior smile of friends. Whenever a man “turns over a new leaf” he has this insane gigle to face. The drunkard may be less ashamed of getting drunk than of breaking to a crony the news that he has signed the pledge. Strange, but true! And human natur must be counted with. Of course, on a few stern spirits the effect of that smile in merely to harden the resolusion. But on the majority its influense is deleterious. Therefore don’t raise any flag. Say nothing. Work as unobtrusively as you can. When you have won a battle or two you can begin to wave the banner, and then you will find that the miserable, pitiful, ironic, superior smile will die away erre it is born. 

The third possible cause that you did not re-arange you day. Idler and time-waster though you have been, stil you had done something during the twenty-four hours. You went to work with a kind of dimm idea that there were twenty-six hours in every day. Something large and definite has to be dropped. You space In the rank jungle of the day has to be cleered and swept up for the new operations. Robbing yourself of sleep won’t help you, nor trying to “squeese in” a time for study between two other times. Use the knife, and use it freely. If you mean to read of think half an hour a day, arrange for an hour. A hundred per cent margin is not to much for a beginner. Do you ask me where the knife is to be used? I should say that in nine cases out of ten the rites of the cult of the body might be abreviated. I resently spent a week-end in a London suburb, and I was staggered by the wholesale attention given to physical rekreation in all its forms. It was gigantic debauch of the muscles on every side. It shocked me. “Poor withering mind!”
`