export const nameCityMapping = {
    'Black': 'Chicago',
    'Everett': 'Baltimore',
    'Ward': 'Buffalo',
    'Smith': 'Philadelphia',
    'Thompson': 'Minneapolis',
    'Dixon': 'Pittsburg',
    'Barton': 'Rochester',
    'Mayer': 'Boston',
    'Newton': 'New York',
    'Murphy': 'St. Paul',
    'Johnson': 'Pittsburg',
    'Thomas': 'Philadelphia',
    'Wells': 'St.Paul',
    'Howard': 'Buffalo',
    'Lawrence': 'Chicago',
    'Palmer': 'Baltimore',
    'Scott': 'Boston',
    'Duffy': 'Minneapolis',
    'Henderson': 'New York',
    'Schwartz': 'Minneapolis',
    'Hyde': 'Chicago',
    'Beck': 'Baltimore',
    'Watkins': 'St. Paul',
    'Barrett': 'Buffalo',
    'Phillips': 'Philadelphia',
    'Rogers': 'Rochester',
    'Lloyd': 'Boston',
    'Williams': 'Pittsburg',
    'Dewey': 'Minneapolis',
    'Martin': 'Chicago',
    'Moore': 'Philadelphia',
    'Carter': 'Rochester',
    'Evans': 'Pittsburg',
    'Foster': 'Minneapolis',
    'Jones': 'St. Paul',
    'Custer': 'New York',
    'Taylor': 'Baltimore',
}